### ISSUE TITLE
Wicket Vs WicketStuff version check

### ISSUE THREAD

**Issue by ilgrosso** [MarcGiffing/wicket-spring-boot#157]
At the moment Wicket is at 8.5.0 while WicketStuff is at 8.4.0.
Artifacts from such two different groups are compatible since Wicket uses semantic versioning, and major version is the same.

This check [1] could be improved to:
* exact match for `org.apache.wicket` dependencies
* major version match for `org.wicketstuff` dependencies

Moreover, same check for `org.wicketstuff` could be performed against `com.googlecode.wicket-jquery-ui`.

WDYT?

[1] https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/app/verifier/WicketDependencyVersionChecker.java#L60-L66

**Comment by solomax** [comment]
`wicket-jquery-ui` is being rarely updated these days, so such improvement is a must

**Comment by MarcGiffing** [comment]
My intention was to provide a hint to the user to also update the wicketstuff dependencies. The user was free to disable the error and only show a log output. Also if its not needed due to the semantic versioning there could be useful bugfixes. But there are two thumbs up...soo ;-) jquery-ui wasn't checked so far.
