### ISSUE TITLE
Provide Documentation for spring-boot-context

### ISSUE THREAD

**Issue by lazaridis-com** [MarcGiffing/wicket-spring-boot#47]
Some questions, thus I can provide some basic docu for the spring-boot-context module.

* What does this code mainly do?
* What is the reason to keep this code in a separate module?

**Comment by MarcGiffing** [comment]
The wicket-spring-boot-context module can be used to create custom auto configuration classes. I've moved the code to this module so that a writer of an auto configuration (extension) class does not have to add the wicket-spring-boot-starter as a dependency.

All dependencies in the wicket-spring-boot-context module are scoped as provided so the user of the context module is not forced to use any spring/wicket dependencies.

Each configuration class should marked with the annotation @ApplicationInitExtension and has to implement WicketApplicationInitConfiguration.

In this module resists also common exceptions which should be used on e.g. configuration errors.

Here is also the place for common configuration checks which can be used by other projects. I've create a annotation @ConditionalOnWicket which can be used to activate configuration only on a specific wicket version.

**Comment by MarcGiffing** [comment]
https://github.com/MarcGiffing/wicket-spring-boot/pull/49
