### ISSUE TITLE
Rework Documentation

### ISSUE THREAD

**Issue by lazaridis-com** [MarcGiffing/wicket-spring-boot#53]
In order to simplify usage of the wicket-starter, the documentation should be reworked.

- [ ] Each module should contain a README
- [x] Move documentation from Root to the relevant modules
- [ ] Simplify documentation

@MarcGiffing  I'll do this task, please see if it's ok for you as described.

**Comment by MarcGiffing** [comment]
The problem is, that you can't include documentation on github. Only the links to the file will be shown. You couldn't include the content. I whould like to have on enough information in the parent module:
https://github.com/MarcGiffing/wicket-spring-boot

But you don't want to create a README for each extension?

In general I'm glad for documenation support with consideration of my statement above.

Alternatively we can use githubs wiki: https://github.com/MarcGiffing/wicket-spring-boot/wiki

**Comment by lazaridis-com** [comment]
documentation = README's, close to the functionality, and yes, one for each module.

Let me just do it, if you don't like it, you can revert or reject it.

Your current documentation is a mess. You possibly don't realize this, because you're familiar with all the stuff.

**Comment by lazaridis-com** [comment]
@MarcGiffing , please try to not change the README's until I'm finished. You can see how it looks on my fork

https://github.com/lazaridis-com/wicket-spring-boot

The root README must shrink to just some explanations about the sub-modules, thus a user get's not overwhelmed by the documentation.

A user should be able to ignore modules, **including** their documentation.

**Comment by MarcGiffing** [comment]
Contributions are welcome at any time! But I don't need someone who makes trouble in all projects he contributes to. I'm doing this in my free time and I still want to have a little bit fun -> banned.
