### ISSUE TITLE
Bean not injected when stateless page is used

### ISSUE THREAD

**Issue by tdziurko** [MarcGiffing/wicket-spring-boot#98]
Hi

I have a problem with `wicket-spring-boot` <-> `wicket` integration. Bean annotated with `@Service` is not properly injected into a backing bean that is injected into a statess Page using `@SpringBean` annotation.

Generally:

    @StatelessComponent
    @MountPath("home-page")
    public class HomePage extends WebPage {
    
        @SpringBean
        private HomePageHandler handler;
    }

and

    @Service
    public class HomePageHandler {
    
        private final CommandPublisher commandPublisher;
    
        @Autowired
        public HomePageHandler(CommandPublisher commandPublisher) {
            this.commandPublisher = commandPublisher;
        }
    
        public void executeAction(String name) {
            commandPublisher.publish(name); /// <----------- NPE (commandPublisher is null)
        }
    }

and: 

    @Service
    public class CommandPublisher {
       
        public void publish(String text) {
            eventPublisher.publishEvent(text);
        }
    
    }

Wicket 7.6.0, wicket-spring-boot 1.0.6. 
I have created a a simple starter (https://github.com/tdziurko/wicket-spring-bean-issue) to reproduce the problem. Problem dissapears when page is not stateless (more info in readme in the starter).

**Comment by MarcGiffing** [comment]
OK, it seems that the problem is related to the cglib proxy mechanism which uses wicket and the target class. There should be no NPE if you add an interface and use it instead of the implementation.

Besides the NPE you should get the following exception:

`java.lang.NoSuchMethodError: com.tomaszdziurko.spring_bean_issue.frontend.HomePageHandler.writeReplace()Ljava/lang/Object;
	at WICKET_com.tomaszdziurko.spring_bean_issue.frontend.HomePageHandler$$EnhancerByCGLIB$$33544e69.writeReplace(<generated>) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]`

For now I can't explain why you have to use an interface...

**Comment by martin-g** [comment]
I've just answered at users@.
HomePageHandler needs a default constructor. CGLIB requires it.
Another option is to use Objenesis instead.

On Apr 4, 2017 10:11 PM, "MarcGiffing" <notifications@github.com> wrote:

OK, it seems that the problem is related to the cglib proxy mechanism which
uses wicket and the target class. There should be no NPE if you add an
interface and use it instead of the implementation.

Besides the NPE you should get the following exception:

java.lang.NoSuchMethodError: com.tomaszdziurko.spring_bean_issue.frontend.
HomePageHandler.writeReplace()Ljava/lang/Object; at
WICKET_com.tomaszdziurko.spring_bean_issue.frontend.HomePageHandler$$
EnhancerByCGLIB$$33544e69.writeReplace(<generated>) ~[bin/:na] at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
at sun.reflect.NativeMethodAccessorImpl.invoke(
NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91] at sun.reflect.
DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[na:1.8.0_91]

For now I can't explain why you have to use an interface...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MarcGiffing/wicket-spring-boot/issues/98#issuecomment-291602259>,
or mute the thread
